### ISSUE TITLE
Register our Entries in the murmurations-index (und update it regularly)

### ISSUE THREAD

**Issue by wellemut** [slowtec/openfairdb#384]
https://murmurations.network/ wants to make it esier to share your profile on many maps.
All Entries from kvm can automatically be added to their system and by this be shown of all of their maps.

## Steps to make all kvm profiles availiable on murmurations: 
- The Murmurations-API is defined on swagger: https://app.swaggerhub.com/apis-docs/MurmurationsNetwork/IndexAPI/1.0
- OpenfairDB (Karte von morgen) API: API: https://app.swaggerhub.com/apis/Kartevonmorgen/openfairdb/

1. Create an Json-Schema, based on the options Murmurations offer so far. (in line with shema.org): It is explained here: https://github.com/MurmurationsNetwork/MurmurationsLibrary#creating-a-schema
1. Send all our Entries to their main index (Their Wiki: https://github.com/MurmurationsNetwork/MurmurationsProtocol/wiki/How-to-map-your-sector-or-network)
2. Everytime an entry is updated, send it to murmurations ( based on our recently changed api https://app.swaggerhub.com/apis/Kartevonmorgen/openfairdb/0.10.5#/Entries%2FPlaces/get_entries_recently_changed)

## Steps to import all data into kvm
?

### Next steps for Murmurations
https://murmurations.network/2021/06/16/the-next-few-building-blocks/
(There is already a murmuration Wordpress-Plugin)

**Comment by olisb** [comment]
Hi Helmut -  thanks for creating  this issue  Geoff, Adam and I will try to help as much as we can ;)

**Comment by wellemut** [comment]
@olisb I started comparing the fields from the Systems-Change Map and our kvm.

Converting our entries in such a Schema should be no problem
![grafik](https://user-images.githubusercontent.com/15019030/137634980-670e809c-0f06-4711-a3a3-3d90aa659be7.png)

But when getting the Data from your plattform, we really face the question, if the entry is non-profit (Initiatives, Movemnts) or for-profit (Companies...). As long as you only map in the non-profit sector, it is quite easy. But as soon as people use your plattform for commercial purposes, it will be very intresting, if you could differenciat that.

- [ ] Could you create a Schema for alle Entries comming from our map? You know it the best and probably you are much faster than me. Here you see my first try: https://github.com/MurmurationsNetwork/MurmurationsLibrary/compare/master...wellemut:patch-1
  - Here is a JSON example of the data we provide: https://kartevonmorgen.org/api/v0/entries/05036857230a4d11913471e5334c2ef9  or better use the directlink for our databas OpenFairDB https://api.ofdb.io/v0/entries/05036857230a4d11913471e5334c2ef9 (Its your entry: https://kartevonmorgen.org/#/?entry=05036857230a4d11913471e5334c2ef9)

- [ ] Could Adam write this script, based on the jsons, he will recieve from this endpoint? https://app.swaggerhub.com/apis/Kartevonmorgen/openfairdb/0.10.5#/Entries%2FPlaces/get_entries_recently_changed

- [ ] Additionally, the places from our map should appear on other schemas, depending, which tags they have on our map. I.E. an Entry with the tag #Systemschange should be on Carolines map, a place with the tag #solidarianeconomy should appear on "Solidarity Economy Intiatives". Like this, all Schemas in your system should have one tag (or even more) that connects places from our map to this schema. And the script, that takes all new entries from our map to your index, has to check, if any of the entries tags, matches a tag for a specific schema on your system and add it there too.

**Comment by Photosynthesis** [comment]
Fantastic work @wellemut! Yes, I will work on the schema for KVM map entries. I think the best approach for this is to as much as possible include all of the properties available in the KVM data. We will use existing Murmurations fields where applicable, and define new fields as necessary. This should be fairly straightforward. A couple of questions:

- Running the /categories endpoint in Swaggerhub gives me some information about what categories are about, but if you have additional info on the category property, or thoughts about how it's intended to be used in the future, it could be helpful for sorting out how it should be identified and described in the Murmurations context. 
- How do you use the ratings property? Part of our eventual road map is to build trust linkages into Murmurations, so that we can track the reputation of entities and allow aggregators to choose what level of trust they might want to require for nodes to be included in their results. I'm curious how you're using ratings, and if this is documented somewhere.

**Comment by wellemut** [comment]
- **Categories**: They should define overall types of entries. So far we Have 
  - Organisations:
    - Initiatives (non-profit, movemets)
    - Companies (for-profit, services)
  - Events
Future Additional Categories could be
  - People
  - Products/Things
So we are not planning of having more than 5 Types

- **Ratings**: Can ether be a partnership in a network/certification or a certain level of sustainability. (It is never ment for an individual rating " I like the food there...")
  - Further description of the current beta-rating is here https://blog.vonmorgen.org/en/positivefactors/
  - Next year, this function will be extended:
    - For every systainablity-network, where an Initiative is part of, it should get a rating. Kind of a certificate, that this is really true. This is why we need a representative or an API from every movement, to prove the membership and remove it, if its wrong/outdated. 
    - All current Partner-Movements are in this Glossary of Change: https://glossardeswandels.de/
    - So this rating idea fits very well to your tracking of entries-reputations.

**Comment by Photosynthesis** [comment]
Hallo @wellemut  -- after a long delay while we sorted out some questions around versioning of fields and other details, we now have a Karte von Morgen schema ready for testing.

The schema is in the staging branch of the Murmurations library here: https://github.com/MurmurationsNetwork/MurmurationsLibrary/blob/staging/schemas/karte_von_morgen-v1.0.0.json

**Comment by Photosynthesis** [comment]
Regarding the script for making KVM data accessible to the Murmurations network, the simplest approach to this has two pieces:
 - An endpoint that provides data on a single entity as JSON matching the schema
 - A POST request to inform the Murmurations index when entities are added or updated

What would be the best way to implement this? Could you see adding the endpoint in the OFDB code (or as an optional format of an existing endpoint)? If so, perhaps you or your developer(s) could give some architectural recommendations as to how this should be implemented, and then I could work on the code?

**Comment by wellemut** [comment]
Thank you very much @Photosynthesis 

If I understand it correctly, 
- you need something like our "recently-Changed" call https://api.ofdb.io/v0/entries/recently-changed, 
- but in your format. https://github.com/MurmurationsNetwork/MurmurationsLibrary/blob/staging/schemas/karte_von_morgen-v1.0.0.json

I guess it makes senss to build a script that makes this post request in your format from our recently-changed.. In Mai we might have some financing for this, if this format is used for larger target groups till then.

**Comment by wellemut** [comment]
An Export of all entries was send to @Photosynthesis for testing a new index.

**Comment by wellemut** [comment]
It is all live in our index now here:
https://index.murmurations.network/v2/nodes?schema=karte_von_morgen-v1.0.0

There are 25,363 entries, which is all of the data minus the ones without a primary_url (a.k.a., homepage ).

We are polling the /entries/recently-changed endpoint every hour to keep our database in sync with yours.

**Comment by wellemut** [comment]
Markus research

Homepage: https://murmurations.network/
Why is this interesting?

    it's extensible
    it's designed for a similar use case
    it's quite simple
    it uses simple static json files
    it uses indexes (a.k.a. aggregators)

What is not so attractive for this project?

    no concept for calendar events

https://codeberg.org/slowtec/fairsync/src/branch/main/doc/src/technologies/murmurations.md

**Comment by geoffturk** [comment]
@wellemut Can you give some detail on what you mean by "no concept for calendar events"? Schema definitions are pretty flexible so I would like to understand what you want to achieve to see if it is possible. Thanks.

**Comment by wellemut** [comment]
> @wellemut Can you give some detail on what you mean by "no concept for calendar events"? Schema definitions are pretty flexible so I would like to understand what you want to achieve to see if it is possible. Thanks.

Alright, so we could just invent a new definition. That's great 

@flosse and Joachim will do a call with you.
