### ISSUE TITLE
D. c) Token-Based Direct-Links from Mailnotification

### ISSUE THREAD

**Issue by wellemut** [slowtec/openfairdb#396]
>Direktlinks mit Token erstellen, mit denen direkt aus den Mailnotifications heraus eine einmalige Statusänderung am Eintrag gemacht werden können, z.B.: - confirmed (falls aktuell) - oder archived (falls geschlossen), ohne dass sich Nutzer*innen dafür einloggen müssen  

Direktlinks-Commands with one-time Token, valid for (2 Tage)

1. Direktlinks erstellen für 
  a. Bestätigen **Entry is still up to date** (link to the entry with a certain token, that will just edit the status to "confirmed") 
  b. und Archivieren **Archive this entry** (will directly archive/ delete this entry form the map)
2. Backend muss direktlinks mit 1Mal tokes verarbeiten 
3. Token produzieren, die für eine Aktion verwendet und nur D (=60) Tage gültig sind.

Direktlinks mit Token erstellen, mit denen direkt aus den Mailnotifications heraus eine einmalige Statusänderung am Eintrag gemacht werden können, z.B.: - confirmed (falls aktuell) - oder archived (falls geschlossen), ohne dass sich Nutzer*innen dafür einloggen müssen

**Comment by flosse** [comment]
Done in #457
