### ISSUE TITLE
Import Bug

### ISSUE THREAD

**Issue by wellemut** [slowtec/openfairdb#411]
(Needed to do the Import: https://github.com/orgs/kartevonmorgen/projects/8#card-84214259) 

### To reproduce 

1. go to the folder of the file `cd C:\Users\Helmut\Wechange\Aalen Karte von Morgen`
  1.2 file `entries.csv` get it from https://cloud.wechange.de/s/M2DW8DpYcTBbEDF
2. Command `ofdb --api-url https://dev.ofdb.io/ import --opencage-api-key 2049603a30ec4cb8a96c2c7fe662dc96 --report-file import-report.json "entries.csv"`

Reading from CSV was succesful
Error: error decoding response body: expected value at line 1 column 1

Caused by:
    expected value at line 1 column 1

![grafik](https://user-images.githubusercontent.com/15019030/181255425-35aacefa-8acb-4caf-8f6b-f8fb2338a1f3.png)

**Comment by flosse** [comment]
This is not a bug, but a lack of error handling.

With #398 you get an error message that you are using an invalid license.
