### ISSUE TITLE
Fix openapi.yaml

### ISSUE THREAD

**Issue by wellemut** [slowtec/openfairdb#462]
Wenn ich die aktuelle openapi.yaml (https://github.com/kartevonmorgen/openfairdb/edit/main/openapi.yaml) in Swagger importiere https://app.swaggerhub.com/apis/Kartevonmorgen/openfairdb/0.12.2 

gibt er mir diesen Fehler aus: 

![grafik](https://user-images.githubusercontent.com/15019030/213499175-7b946de4-64ce-4e87-8152-c1e7a474cde8.png)

und diese Warnung

![grafik](https://user-images.githubusercontent.com/15019030/213499559-622e6efb-0998-4c88-99dd-b98797e5b431.png)

Muss man das beheben @flosse ?

**Comment by flosse** [comment]
closed in #466
