### ISSUE TITLE
Make backend send account-activiaton and passwort reset mails

### ISSUE THREAD

**Issue by wellemut** [slowtec/openfairdb#509]
## Problem
it is not possible to register on:
- https://api.ofdb.io/ 
- or https://openfairdb.org/
because the users dont get  the mail confirmation link.
Seems that mails in general dont workl

## solution
Start the mail service in the backend...

**Comment by alex0107** [comment]
E-Mail funktioniert wieder



![Image](https://github.com/kartevonmorgen/openfairdb/assets/17063865/5ce57f2f-8d12-4072-878f-bc5712c34017)



![Image](https://github.com/kartevonmorgen/openfairdb/assets/17063865/5020628e-b0c4-4b3c-b053-20700735ed76)

**Comment by wellemut** [comment]
Super, vielen Dank dir @alex0107 

Wurden auch vergangenen Mails nach gesendet?
Oder werden sie nur wenn jetzt verschickt?

**Comment by wellemut** [comment]
@flosse  Wir (bzw. @alex0107 ) hat die Mailsubscription wieder deaktiviert, weil einfach zu viele verschickt wurden.

Dadurch sind aber offenbar auch die Passwort-REset Mails nicht mehr erreichbar.
Wir müssten also beide Services trennen. Könntest du das machen?

**Comment by flosse** [comment]
Das ist alles Konfigurierbar: https://github.com/kartevonmorgen/openfairdb/blob/ee24b1d46e52118396561c35e2b0a9de8eb878ad/src/config/openfairdb.full-example.toml#L39-L44

**Comment by wellemut** [comment]
Super, was genau muss @alex0107 einstellen, damit nur Account relevante Mails und keine subscription updates geschickt werden?

**Comment by wellemut** [comment]
Wir müssen die Reminders raus kommentieren. mit #

```
[db]
connection-sqlite = "openfair.db"
connection-pool-size = 10
index-dir = "idx-dir"

[entries]
accepted-licenses = ["CC0-1.0", "ODbL-1.0"]

[webserver]
cors = false
captcha = false

[geocoding]
gateway = "opencage"

[email]
gateway = "email-to-json-file"

## Geocoding Gateways ##

[gateway.opencage]
api-key = "YOUR-API-KEY"

## Email Gateways ##

[gateway.mailgun]
api-key = "YOUR-API-KEY"
domain = "example.com"
sender-address = "no-reply@example.org"

[gateway.sendmail]
sender-address = "no-reply@example.org"

[gateway.email-to-json-file]
dir = "/tmp/openfairdb-email-tests"

## Reminder Emails ##

# [reminders]
# task-interval-time = "2h"
# send-max = 100
# send-to = ["scouts"]
# send-bcc = ["email-test@example.org"]
# token-expire-in = "30d"

[reminders.scouts]
not-updated-for = "400d"

[reminders.owners]
not-updated-for = "1y"
```

**Comment by wellemut** [comment]
Since version 10 https://github.com/kartevonmorgen/openfairdb/blob/v0.12.10/CHANGELOG.md#v01210-2024-06-07
Mails are confirgurable
1. Account / Registration Mails are allways acitve
2. Subscriptions about changes can be deactivated (default deactivated)
3. Request for update mails can be deactivated (possible since allways) (default deactivated)

Default config: https://github.com/kartevonmorgen/openfairdb/blob/main/src/config/openfairdb.default.toml

@alex0107 wenn du jetzt den Mailserver wieder startest, sollte es also klappen. 

Sollten wir Subcriptoin und Mails aktivieren wollen müssten wir uns daran orientieren: 
https://github.com/kartevonmorgen/openfairdb/blob/3137b9d07b6212736c65ae4d09c28686c608605c/src/config/openfairdb.full-example.toml#L37-L43

To activate notifactions/subscriptions:

send-to = ["scouts, owners"]

[reminders.owners]
not-updated-for = "2y"

[reminders.scouts]
not-updated-for = "800d"

token-expire-in = "90d"

**Comment by wellemut** [comment]
Mail registration is possible again.
