### ISSUE TITLE
Put old backend back on openfairdb.org

### ISSUE THREAD

**Issue by wellemut** [slowtec/openfairdb#510]
## Problem
Pilots cant archive or reject entries, as they used to be able to, because the current backend on https://openfairdb.org/ does not support this function.
![grafik](https://github.com/kartevonmorgen/openfairdb/assets/15019030/66268368-7274-4e1b-bda0-dabfae3cdc15)

## Solution

- [ ] @alex0107 Put back the old backend to the domain https://openfairdb.org/ because this domain is linked in the footer of each entry.

![grafik](https://github.com/kartevonmorgen/openfairdb/assets/15019030/0761f412-fdec-4f75-9c0f-c31f324b02bf)
That brings us back the versioning and archive button.

Merging the functions from the old backend to the new might still take a while: https://github.com/kartevonmorgen/openfairdb/issues/508 @flosse  is working on it.

**Comment by flosse** [comment]
@wellemut please try again

**Comment by wellemut** [comment]
Super, geht wieder perfekt!

**Comment by wellemut** [comment]
Hast du das jetzt umgezogen @flosse 

Oder war das @alex0107 ?

**Comment by flosse** [comment]
> Hast du das jetzt umgezogen @flosse

yes!
